const CHANGE_ACCOUNT_POPUP_VISIBILITY = 'CHANGE_ACCOUNT_POPUP_VISIBILITY';
const CHANGE_CURRENT_LEFT_MENU_ITEM = 'CHANGE_CURRENT_LEFT_MENU_ITEM';
const RETRIEVED_CAMPAIGNS_LIST = 'RETRIEVED_CAMPAIGNS_LIST';
const RETRIEVED_CAMPAIGNS_LIST_ERROR = 'RETRIEVED_CAMPAIGNS_LIST_ERROR';

const CHANGE_CONTACT_US_MESSAGE_TEXT = 'CHANGE_CONTACT_US_MESSAGE_TEXT';
const CHANGE_CONTACT_US_MESSAGE_THEME = 'CHANGE_CONTACT_US_MESSAGE_THEME';

const CHANGE_CURRENT_CAMPAIGN_INDEX = 'CHANGE_CURRENT_CAMPAIGN_INDEX';

const ADD_PAYPAL_CODE = 'ADD_PAYPAL_CODE';
const RETRIEVED_PAYPAL_CONNECT = 'RETRIEVED_PAYPAL_CONNECT';

const CHANGE_REPEAT_DATE_RANGE = 'CHANGE_REPEAT_DATE_RANGE';
const CHANGE_REPEAT_BUDGET = 'CHANGE_REPEAT_BUDGET';
const CALCULATE_BUDGET_REPEAT = 'CALCULATE_BUDGET_REPEAT';

const CHANGE_REPEAT_CAMPAIGN_POPUP_VISIBILITY = 'CHANGE_REPEAT_CAMPAIGN_POPUP_VISIBILITY';
const ALERT_CONTACT_US = 'ALERT_CONTACT_US';

const SHOW_UPLOAD_VIDEO = 'SHOW_UPLOAD_VIDEO';

export default {
  CHANGE_ACCOUNT_POPUP_VISIBILITY,
  CHANGE_CURRENT_LEFT_MENU_ITEM,
  RETRIEVED_CAMPAIGNS_LIST,
  RETRIEVED_CAMPAIGNS_LIST_ERROR,
  CHANGE_CONTACT_US_MESSAGE_TEXT,
  CHANGE_CONTACT_US_MESSAGE_THEME,
  CHANGE_CURRENT_CAMPAIGN_INDEX,
  ADD_PAYPAL_CODE,
  RETRIEVED_PAYPAL_CONNECT,
  CHANGE_REPEAT_DATE_RANGE,
  CHANGE_REPEAT_CAMPAIGN_POPUP_VISIBILITY,
  CHANGE_REPEAT_BUDGET,
  ALERT_CONTACT_US,
  SHOW_UPLOAD_VIDEO,
  CALCULATE_BUDGET_REPEAT
};