const CHANGE_RECOVER_PASSWORD = 'CHANGE_RECOVER_PASSWORD';

const RETRIEVED_RECOVER_PASSWORD_INFO = 'RETRIEVED_RECOVER_PASSWORD_INFO';

const CHANGE_RESET_PASSWORD = 'CHANGE_RESET_PASSWORD';
const CHANGE_RESET_PASSWORD_REPEAT = 'CHANGE_RESET_PASSWORD_REPEAT';

const RETRIEVED_RESET_PASSWORD_INFO = 'RETRIEVED_RESET_PASSWORD_INFO';

const CHANGE_RECOVER_EMAIL_1 = 'CHANGE_RECOVER_EMAIL_1';
const CHANGE_RECOVER_EMAIL_2 = 'CHANGE_RECOVER_EMAIL_2';
const CHANGE_RECOVER_EMAIL_3 = 'CHANGE_RECOVER_EMAIL_3';

const RETRIEVED_RECOVER_EMAIL_INFO = 'RETRIEVED_RECOVER_EMAIL_INFO';
const RETRIEVED_RECOVER_EMAIL_ERROR = 'RETRIEVED_RECOVER_EMAIL_ERROR';

const RETRIEVED_RECOVER_PASSWORD_ERROR = 'RETRIEVED_RECOVER_PASSWORD_ERROR';
const RETRIEVED_RESET_PASSWORD_ERROR = 'RETRIEVED_RESET_PASSWORD_ERROR';
const CLEAR_RECOVER_EMAIL_INFO = 'CLEAR_RECOVER_EMAIL_INFO';

const SAVE_LOCATION_QUERY = 'SAVE_LOCATION_QUERY';

const obj = {
  CHANGE_RECOVER_PASSWORD,
  RETRIEVED_RECOVER_PASSWORD_INFO,
  CHANGE_RESET_PASSWORD,
  CHANGE_RESET_PASSWORD_REPEAT,
  RETRIEVED_RESET_PASSWORD_INFO,
  CHANGE_RECOVER_EMAIL_1,
  CHANGE_RECOVER_EMAIL_2,
  CHANGE_RECOVER_EMAIL_3,
  RETRIEVED_RECOVER_EMAIL_INFO,
  RETRIEVED_RECOVER_EMAIL_ERROR,
  RETRIEVED_RECOVER_PASSWORD_ERROR,
  RETRIEVED_RESET_PASSWORD_ERROR,
  CLEAR_RECOVER_EMAIL_INFO,
  SAVE_LOCATION_QUERY
};

export default obj;
