//registration actions
const CHANGE_REGISTRATION_EMAIL = 'CHANGE_REGISTRATION_EMAIL';
const CHANGE_REGISTRATION_COMPANY_NAME = 'CHANGE_REGISTRATION_COMPANY_NAME';

const CHANGE_REGISTRATION_FIRSTNAME= 'CHANGE_REGISTRATION_FIRSTNAME';
const CHANGE_REGISTRATION_LASTNAME = 'CHANGE_REGISTRATION_LASTNAME';

const CHANGE_REGISTRATION_PASSWORD = 'CHANGE_REGISTRATION_PASSWORD';
const CHANGE_REGISTRATION_PASSWORD_REPEAT = 'CHANGE_REGISTRATION_PASSWORD_REPEAT';

const CHANGE_REGISTRATION_PHONE_NUMBER_PRIMARY = 'CHANGE_REGISTRATION_PHONE_NUMBER_PRIMARY';
const CHANGE_REGISTRATION_PHONE_TYPE_PRIMARY = 'CHANGE_REGISTRATION_PHONE_TYPE_PRIMARY';
const CHANGE_REGISTRATION_PHONE_NUMBER_ALTERNATIVE = 'CHANGE_REGISTRATION_PHONE_NUMBER_ALTERNATIVE';
const CHANGE_REGISTRATION_PHONE_TYPE_ALTERNATIVE = 'CHANGE_REGISTRATION_PHONE_TYPE_ALTERNATIVE';

const CHANGE_REGISTRATION_ADDRESS = 'CHANGE_REGISTRATION_ADDRESS';
const CHANGE_REGISTRATION_CITY = 'CHANGE_REGISTRATION_CITY';

const CHANGE_REGISTRATION_STATE = 'CHANGE_REGISTRATION_STATE';
const CHANGE_REGISTRATION_ZIPCODE = 'CHANGE_REGISTRATION_ZIPCODE';

const CHANGE_REGISTRATION_REFFERED_BY = 'CHANGE_REGISTRATION_REFFERED_BY';

const CHANGE_REGISTRATION_TERMS_CHECKBOX = 'CHANGE_REGISTRATION_TERMS_CHECKBOX';

const RETRIEVED_REGISTRATION_USER_INFO = 'RETRIEVED_REGISTRATION_USER_INFO';

const RETRIEVED_REGISTRATION_ERROR = 'RETRIEVED_REGISTRATION_ERROR';
const CHANGE_REGISTRATION_COUNTRY = 'CHANGE_REGISTRATION_COUNTRY';

//general actions
export const UNHANDLED = 'UNHANDLED';

const obj = {
    CHANGE_REGISTRATION_EMAIL,
    CHANGE_REGISTRATION_COMPANY_NAME,
    CHANGE_REGISTRATION_FIRSTNAME,
    CHANGE_REGISTRATION_LASTNAME,
    CHANGE_REGISTRATION_PASSWORD,
    CHANGE_REGISTRATION_PASSWORD_REPEAT,
    CHANGE_REGISTRATION_PHONE_NUMBER_PRIMARY,
    CHANGE_REGISTRATION_PHONE_TYPE_PRIMARY,
    CHANGE_REGISTRATION_PHONE_NUMBER_ALTERNATIVE,
    CHANGE_REGISTRATION_PHONE_TYPE_ALTERNATIVE,
    CHANGE_REGISTRATION_ADDRESS,
    CHANGE_REGISTRATION_CITY,
    CHANGE_REGISTRATION_STATE,
    CHANGE_REGISTRATION_ZIPCODE,
    CHANGE_REGISTRATION_REFFERED_BY,
    CHANGE_REGISTRATION_TERMS_CHECKBOX,
    RETRIEVED_REGISTRATION_USER_INFO,
    RETRIEVED_REGISTRATION_ERROR,
    CHANGE_REGISTRATION_COUNTRY,
    UNHANDLED
};

export default obj;
