//login actions
const CHANGE_LOGIN_EMAIL = 'CHANGE_LOGIN_EMAIL';
const CHANGE_LOGIN_PASSWORD = 'CHANGE_LOGIN_PASSWORD';
const CHANGE_REMEMBER_ME_CHECKBOX = 'CHANGE_REMEMBER_ME_CHECKBOX';
const RETRIEVED_LOGIN_USER_INFO = 'RETRIEVED_LOGIN_USER_INFO';
const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
const RETRIEVED_LOGIN_ERROR = 'RETRIEVED_LOGIN_ERROR';
const RETRIEVED_AUTHORIZATION_HEADER = 'RETRIEVED_AUTHORIZATION_HEADER';
const UPDATE_USER_INFO = 'UPDATE_USER_INFO';

//general actions
const UNHANDLED = 'UNHANDLED';

const obj = {
    CHANGE_LOGIN_EMAIL,
    CHANGE_LOGIN_PASSWORD,
    CHANGE_REMEMBER_ME_CHECKBOX,
    RETRIEVED_LOGIN_USER_INFO,
    RETRIEVED_LOGIN_ERROR,
    UNHANDLED,
    RETRIEVED_AUTHORIZATION_HEADER,
    USER_LOGGED_OUT,
    UPDATE_USER_INFO,
};

export default obj;
